### ISSUE TITLE
User input progress bar is misaligned

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2985]
## Bug Description

The persistent progress bar on the user input app is a bit misaligned compared to the design.

## Screenshots

Current alignment
| Source | Start | End |
| --- | --- | --- |
| Current | ![image](https://user-images.githubusercontent.com/1621608/111627745-117d5e00-87f8-11eb-9cd6-0d905b948bcd.png) | ![image](https://user-images.githubusercontent.com/1621608/111628261-b5ffa000-87f8-11eb-8357-588bb9da1039.png) |
| Design | ![image](https://user-images.githubusercontent.com/1621608/111627787-1e01b680-87f8-11eb-99f0-581edfb3f87e.png) | ![image](https://user-images.githubusercontent.com/1621608/111628303-c0219e80-87f8-11eb-8f1e-3a60095353bb.png) |

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The persistent progress bar on the user input app should align with the start/end of the content area below it
* The width and alignment should match that of the design

## Implementation Brief
* Edit `assets/js/components/user-input/UserInputQuestionnaire.js` to add the `className` prop to the `settingsProgress` `ProgressBar` component, having the value: `googlesitekit-user-input__question--progress`.
* Using `assets/sass/components/user-input/googlesitekit-user-input-questions.scss`,
	* Add the `googlesitekit-user-input__question--progress` class with the following styles:
		* center the component horizontally using margin left and margin right `auto`
		* add a `max-width` of `100%` minus the padding on either sides applied on the content container on different breakpoints. For e.g.
			```css
			.googlesitekit-user-input__question--progress {
				margin: 0 auto;
				max-width: calc(100% - #{$grid-gap-phone * 2});

				@media (min-width: $bp-tablet) {
					max-width: calc(100% - #{$grid-gap-desktop * 2});
				}
			}
			```

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Check that the user input progress bar is now correctly aligned with the content below it as described in the AC at all break points.

## Changelog entry

* Update styles of the progress bar on the User Input Settings screens.
