### ISSUE TITLE
Icons overlapping idea title.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#3839]
## Bug Description
When the browser is resized to 960px, upon hovering an idea, the icons are displayed on top of the idea name.

## Steps to reproduce

1. Go to Site Kit dashboard
3. Scroll down to Idea Hub widget
4. Resize browser to 960px
5. Hover a suggested idea.

## Screenshots
<img src=https://user-images.githubusercontent.com/31818/129164142-b4c2258c-59e3-4ee2-beef-b4486b595c18.png width=400 />

## Additional Context

 - Browser: Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For viewports where the Idea Hub widget appears in a narrow state (even if this viewport is technically not "mobile"), the buttons on each idea should appear below the idea rather than on the right of the idea, similar to how it is in the current mobile layout.

## Implementation Brief

Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js` and `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`:
* Replace the grid layout with normal `div`s:
  * Replace the `<Grid>` and `<Cell>` with `<div>`s with the same `className` attributes (`.googlesitekit-idea-hub__idea--actions` and `.googlesitekit-idea-hub__idea--details` respectively). 
  * The `<Row>` can be replaced with a div with a suitable className (`div.googlesitekit-idea-hub__idea--wrapper` for example).
  * Remove any `mdc-layout-grid-*` CSS that is now redundant.
* Refactor the layout CSS:
  * For viewports below `$bp-xlarge` (1280), use a `display: block`-based layout, such that the `.googlesitekit-idea-hub__idea--actions` wraps underneath the `.googlesitekit-idea-hub__idea--details`.
  * For viewports above `$bp-xlarge`, switch to a flex-based layout, such that the two divs are inline
  * [ The media query](https://github.com/google/site-kit-wp/blob/5f39c77b540ac5b36e9a4f678287720b32dc833c/assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss#L136) which adds a `display: none` rule to the `.googlesitekit-idea-hub__actions--delete`, `.googlesitekit-idea-hub__actions--pin` and  `.googlesitekit-idea-hub__actions--unpin` should be updated so that it applies to viewports above `$bp-xlarge`. This means that the action buttons are all visible when they wrap.
  * Similarly, [the media query](https://github.com/google/site-kit-wp/blob/5f39c77b540ac5b36e9a4f678287720b32dc833c/assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss#L187) that applies `justify-content: flex-end;` to `.googlesitekit-idea-hub__actions` should be updated to apply to viewports above `$bp-xlarge`, so that the action buttons are left-aligned when they wrap.

Here is a gist:
```js
	// Replace grid layout with normal divs
	return (
		<div className="googlesitekit-idea-hub__idea--single">
			<div className="example-css">
				<div className="googlesitekit-idea-hub__idea--details"> ... </div>
				<div className="googlesitekit-idea-hub__idea--actions"> ... </p>
			</div>
		</div>
```
```css

@media (min-width: $bp-xlarge) {
	/* Use a flex layout above 1200 */
	.example-css {
		display: flex;
		padding: 12px 24px; /* use variables, this is just to illustrate */
		justify-content: space-between;
	}

	/* The following action buttons are hidden above 1200 */
	.googlesitekit-idea-hub__actions--delete,
	.googlesitekit-idea-hub__actions--pin,
	.googlesitekit-idea-hub__actions--unpin {
			display: none;
	}

	/* The  actions are right-aligned */
	.googlesitekit-idea-hub__idea--actions {
		justify-content: flex-end;
	}
}

```
And an example screenshot:
| Below 1200 | Above 1200 |
| --- | --- |
| ![Screenshot 2021-08-18 at 16 09 40](https://user-images.githubusercontent.com/2470911/129924924-5b68a728-1083-4fcc-b0a6-7e093e988095.png) | ![Screenshot 2021-08-18 at 16 15 23](https://user-images.githubusercontent.com/2470911/129924928-6e260b7d-82e3-4d4b-bd4b-2b6bf411f3f8.png) |

### Test Coverage

* No new tests required.

### Visual Regression Changes

* Images dealing with the Idea Hub Dashboard widget might need to be updated.

## QA Brief
* Check that the icons in the Idea Hub dashboard widget does not overlap the text content across all breakpoints.

## Changelog entry

* Ensure the icon buttons in the Idea Hub widget do not overlap idea labels.
