### ISSUE TITLE
Address `upload-cloud-storage` action warning

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8093]
## Feature Description

The `upload-cloud-storage` action has an option `process_gcloudignore` which defaults to `true` but will warn if the respective ignore file is not present.

```
Warning: The "process_gcloudignore" option is true, but no .gcloudignore file was found. If you do not intend to process a gcloudignore file, set "process_gcloudignore" to false.
```

We don't include this file so we can set it to `false`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The usage of the `google-github-actions/upload-cloud-storage` action should be updated so that no warnings are raised

## Implementation Brief

* [x] In `.github/workflows/zips.yml` file:
    * [x] In ` google-github-actions/upload-cloud-storage@v1` step of `upload-to-cloud-storage` job. Add `process_gcloudignore: false` option. 

```yml
      - name: Upload PR files
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ${{ github.ref }}
          destination: ${{ env.GCS_BUCKET }}/${{ env.GCS_ROOT_PATH }}/${{ github.ref }}
          parent: false
          process_gcloudignore: false # ADD THIS
```

### Test Coverage

* Not applicable. 

## QA Brief

* Run the Plugin Zip Plugin Zip Files GitHub Workflow and verify the warning is no longer shown at the Upload to GCS step.

## Changelog entry

* N/A
