### ISSUE TITLE
Implement the happy path for creating audiences and the custom dimension via the Setup CTA Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8131]
## Feature Description

Add the Setup CTA Banner to the dashboard, implement the happy path setup logic, and show the success state.

Note that this issue does not include redirecting to OAuth if necessary, this will be implemented separately via https://github.com/google/site-kit-wp/issues/8132.

Additionally, the success state can reuse the component introduced in https://github.com/google/site-kit-wp/issues/8238.

See [setup CTA banner](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.f4g2vm7vw0r0) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If GA4 is connected and has non-zero data over the past 90 days (Site Kit’s maximum date range), then the Setup CTA banner created in #8109 should be displayed directly below the Navigation Bar.
* Assuming the Analytics Edit scope is already granted, clicking on **Enable groups** should:
    * Display the "in progress" state with a spinner icon on the CTA button. 
    * Sync the cached list of audiences (see #8486).
    * Check for any existing "User audiences" (audiences not created by default by Google Analytics nor those created by Site Kit) which have a non-zero user count over the past 90 days.
        * If one or more such User Audiences do exist, they should populate the list of `configuredAudiences`, ordered by user count over the past 90 days, to a maximum selection of two audiences.
        * Following this, if there are less than two audiences in the selection, and one or more of the Site Kit-created "new visitors" and "returning visitors" audiences already exist, they should be added to the list of `configuredAudiences`, to a total maximum selection of two audiences.
        * If the selection is still empty, the "new visitors" and "returning visitors" audiences should be created (using the details below) and added to the list of `configuredAudiences`.
            ```yaml
            - displayName: “New visitors”
            - description: “People who visited the site for the first time”
            - membershipDurationDays: -1      // The longest duration, 540 days.
            - filterClauses<Array>:
              - clauseType: “INCLUDE”
              - simpleFilter:
                - scope: “AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS”
                - filterExpression:
                  - andGroup:
                    - filterExpressions<Array>:
                      - orGroup:
                        - filterExpressions<Array>:
                          - dimensionOrMetricFilter:
                            - fieldName: “newVsReturning”
                            - stringFilter:
                              - matchType: “EXACT”
                              - value: “new”
                      - orGroup:
                        - filterExpressions<Array>:
                          - notExpression:
                            - dimensionOrMetricFilter:
                              - fieldName: “groupId”
                              - stringFilter:
                                - matchType: “EXACT”
                                - value: “created_by_googlesitekit:new_visitors”

            // The "returning visitors" audience should be configured as above with the following differences.

            - displayName: “Returning visitors”
            - description: “People who have visited your site at least once before”
            - filterClauses<Array>:
                - ...
                  - stringFilter:
                      - value: “returning”
                - ...
                  - stringFilter:
                      - value: “created_by_googlesitekit:returning_visitors”
            ```
    * Check if the `googlesitekit_post_type` custom dimension is already created for the property, and if not, then create this custom dimension as per the definition already in the plugin:
        ```javascript
        googlesitekit_post_type: {
            parameterName: 'googlesitekit_post_type',
            displayName: 'WordPress Post Type',
            description: 'Created by Site Kit: Content type of a post',
            scope: 'EVENT',
        }
        ```
    * The Setup CTA component should disappear.
    * The [Setup Success Notice](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1415-15958&mode=design&t=aGVPp2WK9Q8lOg9O-0) component should be displayed as per the Figma mock.
        * Clicking on the **Got it** button should dismiss the notice.
        * Clicking on the **Show me** button should do nothing for now but will eventually scroll to the new widget area.

## Implementation Brief
* [x] In `includes/Modules/Analytics_4/Audience_Settings.php`
    * [x] Change the default value of `configuredAudiences` to `null`.

* [ ] The `isPropertyPartialData` and `isAudiencePartialData` selectors implemented in #8141 determines whether the property has been in partial data state for the currently selected date range. This cannot be used directly here, as we need to know this for the "last-90-days".  
    * [ ] A new set of selectors that computes essentially the same thing with a max range can be created for determining this, with essentially the same logic for [`isResourcePartialData`](https://github.com/google/site-kit-wp/blob/708725ac14f1ab5938bfea5be089f1b7ebc70827/assets/js/modules/analytics-4/datastore/partial-data.js#L390C2-L435) the following alteration. 
    * [ ] Instead of Getting the `startDate` from `getDateRangeDates`, get the `referenceDate` using `getReferenceData` selector, and calculate the start date using `getPreviousDate` function, with `91` days (90 days + one day offset). 

* [ ] In `assets/js/modules/analytics-4/datastore/audiences.js` file, create `enableAudienceGroup` action. 
    * [ ] Use `syncAvailableAudiences` to sync the list of available audience.
    * [ ] Get list of cached audiences using the `getAvailableAudiences` selector. 
    * [ ] Filter the `availableAudiences` by `USER_AUDIENCE` type and perform the same partial data for 90-days check using the newly introduced selector. ie. `userCreatedAudiencesWithData`
    * [ ] Create a report request using `getReport` selector using the following args. 
        * [ ] `startDate`: property creation time. 
        * [ ] `endDate`: reference date. 
        * [ ] `dimensions`: `[ "audienceResourceName" ]`
        * [ ] `metrics`: `[ "totalUsers" ]`
        * [ ] `dimensionFilters`: `userCreatedAudiencesWithData`
    * [ ] If there is no error and the report succeeds, take the dimensions with most total users. 
    * [ ] If there are one or more audiences, add to a temporary `audiencesToConfigure`, up to two audience, ordered by the user count.
    * [ ] If the `audiencesToConfigure` is less than two, check if there are `SITE_KIT_AUDIENCE` type of audiences, and add them to the list up to two in the following priority order `new-visitors`, `returning-visitors`. 
    * [ ] If `audienceToConfigure` is empty at this point, create the audiences defined in AC using the `createAudience` action and added to `audienceToConfigure`.  
    * [ ] Check if the `googlesitekit_post_type` custom dimension already exists in the current property using the `hasCustomDimensions` selector. 
    * [ ] If It doesn't exist, create it using `createCustomDimensions` action. 
    * [ ] Finally, Set the `audienceToConfigure` as `configuredAudiences` using the `setConfiguredAudiences` and save the Settings by `saveConfiguredAudiences`.

* [x] In the `AudienceSegmentationSetupCTAWidget` component:
    * [x] Remove the `title` and `description` prop and inline the copy passed from the `AudienceSegmentationSetupCTAWidget.stories` to the component itself. 
    * [ ] Get current property ID using `getPropertyID` selector. 
    * [ ] Determine if the property is in partial data state for 90day range using the newly introduced selector. 
    * [ ] Determine whether current user has analytics `EDIT_SCOPE` using the `hasScope` selector. 
    * [ ] Get the currently configured audiences using `getConfiguredAudiences` selector. 
    * [x] Update the `onEnableGroups` callback to handle creating audience and custom dimensions. 
        * [x] call `await enableAudienceGroup` action here when `ANALYTICS_EDIT_SCOPE` is available after setting `isSaving` to `true`, so the CTA changes to `Enabling groups` with a spinner on the right of it. (already implemented). 
    * [x] If `configuredAudiences` has been set or `isPropertyPartialData90Days` is true, return `null` from the component. 

* [x] Create `AudienceSegmentationSetupSuccessSubtleNotification` in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard` folder. 
    * [x] It should be similar to `GA4AdSenseLinkedNotification`. Make any additional CSS changes to match the look in Figma as needed using a new class. ie. `googlesitekit-subtle-notification--audience-setup-success`
    * [x] It should be displayed when `configuredAudiences` is set and this notification has not been dismissed.

* [x] Render the `AudienceSegmentationSetupCTAWidget` in `DashboardMainApp` when `audienceSegmentation` feature flag is enabled. 

* [x] Render the `AudienceSegmentationSetupSuccessSubtleNotification` in `SubtleNotifications` when `audienceSegmentation` feature flag is enabled. 

### Test Coverage

* Add test coverage for the newly introduced selectors.
* Add test coverage for `enableAudienceGroup`action. 
* Update any failing tests. 

### Prerequisites

In order to fully test this issue from a user's perspective, you will need the following:

- An Analytics property which does not have data over the past 90 days.
- Multiple Analytics properties which do have data over the past 90 days:
  - A property which has no user-defined audiences set up.
  - A property which has one user-defined audience set up which has data over the past 90 days, and any number of additional user-defined audiences which don't have data over the past 90 days.
  - A property similar to the one in the point above but which has two user-defined audiences which have data.
  - A property similar to the one in the point above but which has three user-defined audiences which have data.

Refer to the [set up via the Analytics UI](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.e98hcflf4q76) section in the design doc for some pointers on audience creation - note that these instructions are for manually creating the "new visitors" and "returning visitors" audiences, but they can be tweaked for creating other audiences with arbitrary criteria which will be needed for testing here. Once these audiences are created they will need to be populated by some site traffic which meets their criteria. For more info see the linked Google [support page](https://support.google.com/analytics/answer/9267572#zippy=%2Cin-this-article), and also the [testing plan considerations](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.wl370qtxfr88) section in the design doc for additional info on how to examine audiences in reports in the Analytics UI, so as to verify that the audiences are being populated with data (their total user counts can be examined to help verify audiences are sorted correctly).

### Testing

- Set up Site Kit.
- Connect the Analytics property which does not have data over the past 90 days to verify the Setup CTA Banner is _not_ displayed in this scenario.
- For the Analytics properties which _do_ have data over the past 90 days:
  - Reset Site Kit, set it up again and connect the given property.
  - Verify the Setup CTA Banner is displayed on the main dashboard (please note the banner has already been tested in Storybook via #8109 so we shouldn't need to get into any minor differences with the Figma design here).
  - Click the **Enable groups** CTA; the spinner should appear in the button while the setup flow continues.
  - Use the property which has no user-defined audiences to verify the flow where the "new visitors" and "returning visitors" audiences are created and added to the audience selection.
  - Use the property which has one user-defined audience with data to verify the flows where:
    - The single user-defined audience is added to the selection.
    - The "new visitors" or "returning visitors" audience is also added to selection when these exist (follow the [set up via the Analytics UI](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.e98hcflf4q76) to manually create these for testing this point).
  - Use the property which has two user-defined audiences with data to verify the flow where the audiences are added to the selection, ordered by total user count.
  - Use the property which has three user-defined audiences with data to verify the flow where the top two audiences are added to the selection, ordered by total user count.
  - Verify the `googlesitekit_post_type` custom dimension is created if it doesn't already exist (custom dimensions can be viewed for a given Analytics property under **Admin > Property settings > Data display > Custom definitions**, and see this Google [support page](https://support.google.com/analytics/answer/14240153?hl=en) for an entry point on custom dimension documentation).
  - Note that the SK-created audiences and custom dimensions can be archived via the Analytics UI in order to re-test their creation.
- Upon completion of each setup flow:
  - Verify the Setup CTA Banner disappears.
  - Verify the Setup Success Notice is displayed. This should broadly follow the Figma design, but should more closely align with the existing implementation for other banners of this style, for example see the Setup Success Subtle Notification (Ads) component in [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccesssubtlenotification--ads).

To verify the synced audiences and the resulting audience selections, run the following snippets in the JS console once the setup flow is complete for each scenario:

- Examine the synced audiences, these are returned by the `getAvailableAudiences()` selector:

```js
googlesitekit.data.select("modules/analytics-4").getAvailableAudiences();
```

_Example output:_  
![image](https://github.com/google/site-kit-wp/assets/18395600/714be1df-f527-40c5-a078-5b527049542d)

- Examine the audience selection, this is returned by the `getConfiguredAudiences()` selector:

```js
googlesitekit.data.select("modules/analytics-4").getConfiguredAudiences();
```

_Example output:_  
![image](https://github.com/google/site-kit-wp/assets/18395600/6b27e3b1-2aee-4a07-95d3-39e17ded82ec)

- Cross-reference the values from `getConfiguredAudiences()` with the `name` property in the values returned by `getAvailableAudiences()` to determine which audiences are selected. This snippet can automate this process:

```js
// Store the list of available audiences in a variable:
availableAudiences = googlesitekit.data
  .select("modules/analytics-4")
  .getAvailableAudiences();

// Look up the `displayName` for each audience in the audience selection:
googlesitekit.data
  .select("modules/analytics-4")
  .getConfiguredAudiences()
  .map(
    (name) =>
      availableAudiences.find((audience) => audience.name === name).displayName
  );
```

_Example output:_  
![image](https://github.com/google/site-kit-wp/assets/18395600/5d7cf1d1-c506-4e6e-af7d-9b7cf81ecb6a)

## Changelog entry

* Introduce creation of audience groups from Audience Setup Banner.

**Comment by sigal-teller** [comment]
@jimmymadon The new success notification I designed for Audience segmentation is intended to replace all successful setup notifications. We would like to keep consistent but I assume we’ll implement it gradually. This one should be replacing the large white [banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccessbannernotification--module) that we have now. The other one you mentioned (the yellow one) is a warning notification and should be used for other purposes. I updated its design as well in recent designs.

**Comment by techanvil** [comment]
> @techanvil Just wanted to check if this issue deals with adding the fetched User Audiences or the newly created Site Kit audiences to the list of `configuredAudiences`. If so, then this issue will depend on the [issue](https://github.com/google/site-kit-wp/issues/8176#issuecomment-1917719238) that saves the `configuredAudiences` in settings.

Hi @jimmymadon - yes, this issue should deal with setting `configuredAudiences` as you've described. I've updated the dependencies for this and other affected issues (basically changing dependencies from https://github.com/google/site-kit-wp/issues/8130 to https://github.com/google/site-kit-wp/issues/8176 across the board). Thanks for the heads up.

**Comment by marrrmarrr** [comment]
@jimmymadon good catch, we can definitely update this a bit. 
First of all, we should remove the mention of "audiences", as everywhere else we talk about visitor groups. 
For the second part, let's focus on what the new panels actually show.
So I'd suggest: 
"Success! You can now see how your site's traffic breaks down by different visitor groups"
"Get to know how different types of visitors interact with your site: where they come from, how long they stay, what content is most relevant to them, and much more."

**Comment by sigal-teller** [comment]
@jimmymadon Thanks for catching that. @marrrmarrr I think it's a bit too long for success notification text. we need to keep in mind that the user has just seen the CTA banner, we don't need to repeat the messages. The success notification should mainly inform the user that the setup was successful and what are the next steps - there's a new section where he can see this data and we can point him there with "shoe me". 
Maybe we can use your suggestion to update the CTA banner copy to be more general (we also use the same terminology that Jimmy spotted for the new and returning in the banner).

**Comment by techanvil** [comment]
Hi @jimmymadon, this AC is almost there, however, and with apologies for the moving target, the design doc has or may change a bit in a couple of relevant areas, which means the AC will need an update, but it will need to wait until these changes are finalised.

The current AC is _slightly_ off with regard to what is now the old setup logic because it focuses on checking user-created audiences, thus missing the edge case where the new/returning visitors audiences are already created and should be considered for inclusion in the initial audience selection, plus the potential to include the "Purchasers" audience if it's "active".

However, this focus on the user-created audiences has made me realise that we _should_ update the setup logic to raise the priority of user-created audiences for inclusion. As a result, I've proposed a refinement to the setup logic in the design doc. This needs to be approved by Mariya and Evan, who I've tagged on a [comment thread](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABFcMwmwk).

Beyond this, there are a couple of points with regard to the audience configuration:
- We have that [open thread](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABDuF1CmU) on the design doc where we are considering appending a string along the lines of "Created by Google Site Kit - do not edit" to the descriptions.
- It's a small point, but it would be worth pointing out that the "Returning visitors" definition is only a diff of the "New visitors" definition and not the whole thing.

Lastly, we might want to hold off until the copy for the Setup Success Notice has been updated in Figma before moving this to IB (or, leave a note in the AC or IB section to bring attention to the fact that it's liable to change).

**Comment by zutigrm** [comment]
Hi @techanvil @jimmymadon one note for the `configureAudience` object in AC, we need to have `orGroup` in `andGroup` before applying the `dimensionOrMetricFilter` filter in order for `create-aduience` endpoint to work. Also `Value` should be `value`, and `adsPersonalizationEnabled` is output only field, computed by Analytics, same like `name` parameter, so it isn't included in audience object when creating audience.

Found this out while working on #8108 . I added suggestion in design doc as well

```
- displayName: “New visitors”
- description: “People who visited the site for the first time”
- membershipDurationDays: -1      // The longest duration, 540 days.
- filterClauses:
    - clauseType: “INCLUDE”
    - simpleFilter:
        - scope: “AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS”
        - filterExpression:
            - andGroup:
                - filterExpressions<Array>:
                    - orGroup:
                        - filterExpressions<Array>:
                            - dimensionOrMetricFilter:
                                - fieldName: “newVsReturning”
                                - stringFilter:
                                    - matchType: “EXACT”
                                    - value: “new”
```
